# fly.toml app configuration file generated for discordbotcreating on 2026-04-08T11:33:18+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discordbotcreating'
primary_region = 'nrt'

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = 'data'
  destination = '/data'

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
